In [1]:
import numpy as np

In [2]:
my_list=[10,20,30,40]


In [3]:
my_numpy=np.array(my_list)

In [4]:
my_list[0]

10

In [5]:
my_list[0]=100

In [6]:
my_list

[100, 20, 30, 40]

In [7]:
my_numpy.mean()

25.0

In [8]:
type(my_list)

list

In [9]:
matrix=[[1,0,0],[0,1,0],[0,0,1],[0,0,0]]


In [10]:
npmatrix=np.array(matrix)

In [11]:
npmatrix.shape

(4, 3)

In [12]:
#arange

In [13]:
range(0,10)

range(0, 10)

In [14]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
np.arange(0,30,3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [16]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [17]:
np.zeros((10,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [18]:
#linspace

In [19]:
my_list2=np.linspace(1,100,100)

In [20]:
np.random.randint(1,9,3)

array([1, 7, 3])

In [21]:
my_list2[4:9:2]=10

In [22]:
my_list2

array([  1.,   2.,   3.,   4.,  10.,   6.,  10.,   8.,  10.,  10.,  11.,
        12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.,  21.,  22.,
        23.,  24.,  25.,  26.,  27.,  28.,  29.,  30.,  31.,  32.,  33.,
        34.,  35.,  36.,  37.,  38.,  39.,  40.,  41.,  42.,  43.,  44.,
        45.,  46.,  47.,  48.,  49.,  50.,  51.,  52.,  53.,  54.,  55.,
        56.,  57.,  58.,  59.,  60.,  61.,  62.,  63.,  64.,  65.,  66.,
        67.,  68.,  69.,  70.,  71.,  72.,  73.,  74.,  75.,  76.,  77.,
        78.,  79.,  80.,  81.,  82.,  83.,  84.,  85.,  86.,  87.,  88.,
        89.,  90.,  91.,  92.,  93.,  94.,  95.,  96.,  97.,  98.,  99.,
       100.])

In [23]:
my_list2[:]=100

In [24]:
my_list2

array([100., 100., 100., 100., 100., 100., 100., 100., 100., 100., 100.,
       100., 100., 100., 100., 100., 100., 100., 100., 100., 100., 100.,
       100., 100., 100., 100., 100., 100., 100., 100., 100., 100., 100.,
       100., 100., 100., 100., 100., 100., 100., 100., 100., 100., 100.,
       100., 100., 100., 100., 100., 100., 100., 100., 100., 100., 100.,
       100., 100., 100., 100., 100., 100., 100., 100., 100., 100., 100.,
       100., 100., 100., 100., 100., 100., 100., 100., 100., 100., 100.,
       100., 100., 100., 100., 100., 100., 100., 100., 100., 100., 100.,
       100., 100., 100., 100., 100., 100., 100., 100., 100., 100., 100.,
       100.])

In [25]:
my_list3=my_list2[2:9]

In [26]:
my_list3[:]=8

In [27]:
my_list2

array([100., 100.,   8.,   8.,   8.,   8.,   8.,   8.,   8., 100., 100.,
       100., 100., 100., 100., 100., 100., 100., 100., 100., 100., 100.,
       100., 100., 100., 100., 100., 100., 100., 100., 100., 100., 100.,
       100., 100., 100., 100., 100., 100., 100., 100., 100., 100., 100.,
       100., 100., 100., 100., 100., 100., 100., 100., 100., 100., 100.,
       100., 100., 100., 100., 100., 100., 100., 100., 100., 100., 100.,
       100., 100., 100., 100., 100., 100., 100., 100., 100., 100., 100.,
       100., 100., 100., 100., 100., 100., 100., 100., 100., 100., 100.,
       100., 100., 100., 100., 100., 100., 100., 100., 100., 100., 100.,
       100.])

In [28]:
new_array=np.random.randint(1,150,25)

In [29]:
new_array

array([ 24, 128,  23,  43,  12, 106,  19,  73,  38,  34,  22,  13,  73,
       127, 118,  69,  74,  10, 144, 119,  87, 129, 111,   7, 141])

In [30]:
new_array>50

array([False,  True, False, False, False,  True, False,  True, False,
       False, False, False,  True,  True,  True,  True,  True, False,
        True,  True,  True,  True,  True, False,  True])

In [31]:
result_array=new_array>50

In [32]:
result_array

array([False,  True, False, False, False,  True, False,  True, False,
       False, False, False,  True,  True,  True,  True,  True, False,
        True,  True,  True,  True,  True, False,  True])

In [33]:
new_array[new_array>50]
new_array[result_array]

array([128, 106,  73,  73, 127, 118,  69,  74, 144, 119,  87, 129, 111,
       141])

In [34]:
new_array.mean()

69.76

In [35]:
lost_array=np.arange(0,30)

In [36]:
lost_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [37]:
lost_array+lost_array


array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58])

In [38]:
lost_array*lost_array

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225, 256, 289, 324, 361, 400, 441, 484, 529, 576, 625,
       676, 729, 784, 841])

In [39]:
lost_array.max()

29

In [40]:
np.max(lost_array)

29

In [41]:
np.sqrt(lost_array)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894,
       4.47213595, 4.58257569, 4.69041576, 4.79583152, 4.89897949,
       5.        , 5.09901951, 5.19615242, 5.29150262, 5.38516481])

In [42]:
#pandas

import pandas

In [43]:
import pandas as pd

In [44]:
#series

In [45]:
my_dict={"James":50,"Lars":60,"Kirk":55,"Rob":65}


In [46]:
pd.Series(my_dict)

James    50
Lars     60
Kirk     55
Rob      65
dtype: int64

In [47]:
age_list=[50,60,55,65]
name_list=["James","Lars","Kirk","Rob"]


In [48]:
pd.Series(age_list,name_list)
import numpy as np

In [49]:
numpy_array=np.arange(0,8)


In [50]:
numpy_array

array([0, 1, 2, 3, 4, 5, 6, 7])

In [51]:
pd.Series(numpy_array)

0    0
1    1
2    2
3    3
4    4
5    5
6    6
7    7
dtype: int64

In [52]:
new_numpy=np.array([10,20,30,40])


In [53]:
pd.Series(new_numpy)

0    10
1    20
2    30
3    40
dtype: int64

In [54]:
pd.Series(data=new_numpy,index=name_list)


James    10
Lars     20
Kirk     30
Rob      40
dtype: int64

In [55]:
my_series=pd.Series(data=new_numpy,index=name_list)

In [56]:
my_series

James    10
Lars     20
Kirk     30
Rob      40
dtype: int64

In [57]:
type(my_series)

pandas.core.series.Series

In [58]:
my_series["Kirk"]=100

In [59]:
my_series

James     10
Lars      20
Kirk     100
Rob       40
dtype: int64

In [60]:
quiz_result1=pd.Series(data=[70,80,90],index=["A","B","C"])


In [61]:
quiz_result2=pd.Series(data=[80,30,50],index=["A","B","C"])

In [62]:
quiz_result1

A    70
B    80
C    90
dtype: int64

In [63]:
quiz_result2

A    80
B    30
C    50
dtype: int64

In [64]:
quiz_result1+quiz_result2

A    150
B    110
C    140
dtype: int64

In [65]:
axam=pd.Series(data=[70,80,90],index=["A","B","C"])

In [66]:
axam2=pd.Series(data=[70,80,90],index=["A","D","C"])

In [67]:
axam+axam2

/usr/local/lib/python3.10/dist-packages/pandas/io/formats/format.py:1458: RuntimeWarning: invalid value encountered in greater
  has_large_values = (abs_vals > 1e6).any()
/usr/local/lib/python3.10/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in less
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.10/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in greater
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()


A    140.0
B      NaN
C    180.0
D      NaN
dtype: float64

In [68]:
my_data=np.array([[10,20,30],[20,30,40],[20,50,10],[10,15,20]])
my_data

array([[10, 20, 30],
       [20, 30, 40],
       [20, 50, 10],
       [10, 15, 20]])

In [69]:
my_names=["nurhat","baydag","hanzade","seyh"]


In [70]:
my_colums=["jan","feb","march"]

In [71]:
my_dataframe=pd.DataFrame(my_data)


In [72]:
my_dataframe

0   1   2
0  10  20  30
1  20  30  40
2  20  50  10
3  10  15  20

In [73]:
my_dataframe[1]

0    20
1    30
2    50
3    15
Name: 1, dtype: int64

In [74]:
new_dataframe=pd.DataFrame(my_data,index=my_names,columns=my_colums)

In [75]:
new_dataframe

jan  feb  march
nurhat    10   20     30
baydag    20   30     40
hanzade   20   50     10
seyh      10   15     20

In [76]:
new_dataframe["feb"]

nurhat     20
baydag     30
hanzade    50
seyh       15
Name: feb, dtype: int64

In [77]:
feb_series=new_dataframe["feb"]

In [78]:
feb_series.mean()

28.75

In [79]:
feb_series.nurhat

20

In [80]:
new_dataframe["jan"].mean()

15.0

In [81]:
new_dataframe[["jan","feb"]]

jan  feb
nurhat    10   20
baydag    20   30
hanzade   20   50
seyh      10   15

In [82]:
new_dataframe.iloc[1:3]

jan  feb  march
baydag    20   30     40
hanzade   20   50     10

In [83]:
new_dataframe["Apr"]=new_dataframe["march"]*2

In [84]:
new_dataframe

jan  feb  march  Apr
nurhat    10   20     30   60
baydag    20   30     40   80
hanzade   20   50     10   20
seyh      10   15     20   40

In [85]:
new_dataframe.drop("seyh",axis=0)

jan  feb  march  Apr
nurhat    10   20     30   60
baydag    20   30     40   80
hanzade   20   50     10   20

In [86]:
new_dataframe.drop("Apr",axis=1)

jan  feb  march
nurhat    10   20     30
baydag    20   30     40
hanzade   20   50     10
seyh      10   15     20

In [87]:
new_dataframe.drop("Apr",axis=1,inplace=True)

In [88]:
new_dataframe

jan  feb  march
nurhat    10   20     30
baydag    20   30     40
hanzade   20   50     10
seyh      10   15     20

In [89]:
new_dataframe["feb"]["nurhat"]

20

In [90]:
boolean_frame=new_dataframe>25

In [91]:
boolean_frame

jan    feb  march
nurhat   False  False   True
baydag   False   True   True
hanzade  False   True  False
seyh     False  False  False

In [92]:
new_dataframe[boolean_frame]

/usr/local/lib/python3.10/dist-packages/pandas/io/formats/format.py:1458: RuntimeWarning: invalid value encountered in greater
  has_large_values = (abs_vals > 1e6).any()
/usr/local/lib/python3.10/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in less
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.10/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in greater
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()


jan   feb  march
nurhat   NaN   NaN   30.0
baydag   NaN  30.0   40.0
hanzade  NaN  50.0    NaN
seyh     NaN   NaN    NaN

In [93]:
new_dataframe[new_dataframe>30]

/usr/local/lib/python3.10/dist-packages/pandas/io/formats/format.py:1458: RuntimeWarning: invalid value encountered in greater
  has_large_values = (abs_vals > 1e6).any()
/usr/local/lib/python3.10/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in less
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.10/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in greater
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()


jan   feb  march
nurhat   NaN   NaN    NaN
baydag   NaN   NaN   40.0
hanzade  NaN  50.0    NaN
seyh     NaN   NaN    NaN

In [94]:
new_dataframe

jan  feb  march
nurhat    10   20     30
baydag    20   30     40
hanzade   20   50     10
seyh      10   15     20

In [95]:
new_dataframe[new_dataframe["march"]>25]

jan  feb  march
nurhat   10   20     30
baydag   20   30     40

In [96]:
new_dataframe

jan  feb  march
nurhat    10   20     30
baydag    20   30     40
hanzade   20   50     10
seyh      10   15     20

In [97]:
new_dataframe.reset_index()

index  jan  feb  march
0   nurhat   10   20     30
1   baydag   20   30     40
2  hanzade   20   50     10
3     seyh   10   15     20

In [98]:
new_dataframe

jan  feb  march
nurhat    10   20     30
baydag    20   30     40
hanzade   20   50     10
seyh      10   15     20

In [99]:
new_dataframe

jan  feb  march
nurhat    10   20     30
baydag    20   30     40
hanzade   20   50     10
seyh      10   15     20

In [100]:
new_dataframe["NewIndex"]=["Jam","Lar","Kir","Robert"]

In [101]:
new_dataframe


jan  feb  march NewIndex
nurhat    10   20     30      Jam
baydag    20   30     40      Lar
hanzade   20   50     10      Kir
seyh      10   15     20   Robert

In [102]:
new_dataframe.set_index("NewIndex")

jan  feb  march
NewIndex                 
Jam        10   20     30
Lar        20   30     40
Kir        20   50     10
Robert     10   15     20

In [103]:
new_dataframe

jan  feb  march NewIndex
nurhat    10   20     30      Jam
baydag    20   30     40      Lar
hanzade   20   50     10      Kir
seyh      10   15     20   Robert

In [104]:
new_dataframe.drop("NewIndex",axis=1,inplace=True)

In [105]:
new_dataframe

jan  feb  march
nurhat    10   20     30
baydag    20   30     40
hanzade   20   50     10
seyh      10   15     20